---
title: "Analysis"
output: html_notebook
---
```{r}

normal_clt <- function(n, m=0, sd=1, k=100) {
  numbers = c()
  
  for (j in 1:n) {
    rndsum = 0
    for (i in 1:k) {
      rndsum = rndsum + runif(1) - 0.5
    }
    numbers = c(numbers, sd*sqrt(12/k)*rndsum + m)
  }
  
  return(numbers)
}

normal_polar = function(m1=0, sd1=1, m2=0, sd2=1) {
  s = 1
  while(s >= 1) {
    v1 = 2*runif(1) - 1
    v2 = 2*runif(1) - 1
    s = v1^2 + v2^2
  }
  
  x1 = v1*sqrt((-2)*log(s)/s)
  x2 = v2*sqrt((-2)*log(s)/s)
  
  return(c(sd1*x1 + m1, sd2*x2 + m2))
}

K = function(z) {
  if (abs(z) <= 1) return(1 - abs(z))
  return(0)
}
getMean = function(x) {
  mean_x = rep(0, ncol(x))
  for (i in 1:nrow(x)) {
    for (j in 1:ncol(x)) {
      mean_x[j] = mean_x[j] + x[i, j]
    }
  }
  return(mean_x/nrow(x))
}
getSd = function(x) {
  m_x = getMean(x)
  sd_x = rep(0, ncol(x))
  for (i in 1:nrow(x)) {
    for (j in 1:ncol(x)) {
      sd_x[j] = sd_x[j] + (x[i, j] - m_x[j])^2
    }
  }
  return(sd_x/nrow(x))
}
getP = function(x, n) {return(nrow(x)/n)}
estimate = function(x, sample, kernel=K, h=1.06*getSd(sample)*nrow(sample)^(-1/5)) {
  if (length(x) != ncol(sample) || length(x) != length(h)) stop("wrong args")
  result = 0
  for (i in 1:nrow(sample)) {
    kmult = 1
    for (j in 1:ncol(sample)) {
      kmult = kmult*kernel((x[j] - sample[i, j])/h[j])/h[j]
    }
    result = result + kmult
  }
  result = result/nrow(sample)
  return(result)
}
getRandPoint = function(dist_func, m1=0, sd1=1, m2=0, sd2=1, k=100) {
  if (identical(dist_func, normal_polar)) {
    return(dist_func(m1, sd1, m2, sd2))
  } else if (identical(dist_func, normal_clt)) {
    return(c(dist_func(1, m1, sd1, k=k), dist_func(1, m2, sd2, k=k)))
  } else {
    return(c(dist_func(1, m1, sd1), dist_func(1, m2, sd2)))
  }
}
```


```{r}
method = c("standard" = rnorm,
               "clt" = normal_clt,
               "polar" = normal_polar)

options = seq(0.1, 0.9, length=15)
results = c()
for (opt in options) {
  
  h=c(1, 1)
  func = method[["standard"]]
  n = 1e4
  p1 = 0.01+opt
  p2 = 1-p1
  
  m11 = 0
  m12 = 0
  m21 = 5
  m22 = 5
  sd11 = 1
  sd12 = 1
  sd21 = 1
  sd22 = 1
  
  x = c()
  y = c()
  for (i in 1:n) {
    if (runif(1) <= p1) x = c(x, getRandPoint(func, m11, sd11, m12, sd12))
    else y = c(y, getRandPoint(func, m21, sd21, m22, sd22))
  }
  x = matrix(x, ncol = 2, byrow = TRUE)
  y = matrix(y, ncol = 2, byrow = TRUE)
  n1 = nrow(x)
  n2 = nrow(y)
  plot(x, ylim = c(min(x[, 2], y[, 2]), max(x[, 2], y[, 2])), 
       xlim = c(min(x[, 1], y[, 1]), max(x[, 1], y[, 1])), pch = 1)
  points(y, pch = 2)
      
  test_len = 200
  test_points = c()
  spread_coef = 1.5
  class = c()
  for (i in 1:test_len) {
    k = 100
    if (runif(1) <= p1) {
      test_points = c(test_points, getRandPoint(func, m11, sd11*spread_coef, m12, sd12*spread_coef, k=k))
      class = c(class, 1)
    } else {
      test_points = c(test_points, getRandPoint(func, m21, sd21*spread_coef, m22, sd22*spread_coef, k=k))
      class = c(class, 2)
    }
  }
  # count error
  estimation = c()
  error = 0
  unclear = 0
  for (i in 1:test_len) {
    est_x = estimate(c(test_points[i*2 - 1], test_points[i*2]), x, h=h)*p1
    est_y = estimate(c(test_points[i*2 - 1], test_points[i*2]), y, h=h)*p2
    
    col = "green"
    
    if (est_x - est_y < 0) {
      estimation = c(estimation, 2)
    } else if (est_x - est_y > 0) {
      estimation = c(estimation, 1)
    } else {
      estimation = c(estimation, 0)
      col = "gray"
    }
    
    if (estimation[i] == 0) {
      unclear = unclear + 1
    } else if (estimation[i] != class[i]) {
      error = error + 1
      col = "red"
    }
    print(paste0(i, " - ",estimation[i],":", col, ", ", est_x-est_y))
    points(test_points[i*2-1], test_points[i*2], pch=estimation[i]+15, col=col, cex=1.5)
  }
  error = error/test_len
  unclear = unclear/test_len
  results = c(results, error+unclear)
  print(paste(error*100, "%; Unclear ", unclear*100, "%"))
  legend("bottomright", 
         legend=paste0("Error ", error*100, "%; Unclear ", unclear*100, "%"))
}

```